### PR TITLE
OCPBUGS-5502: Rebase v1.34.5

### PR DESCRIPTION
**Pull request by tsmetana**
*Issue #, if available:*
https://issues.redhat.com/browse/OCPBUGS-5502

*Description of changes:*
Rebase to the latest upstream version that fixes multiple problems, among others the race described in the OCPBUGS-5502.

Diff to upstream: https://github.com/aws/efs-utils/compare/v1.34.5...tsmetana:rebase-4.12-v1.34.5

### CODE REVIEW

**Comment by jsafrane** [comment]
CI passed twice in 4.13 with the rebased efs-utils
/lgtm
/approve

**Comment by bertinatto** [comment]
/cherry-pick release-4.11
Let's how it looks like in 4.11.

**Pull request merged**
